# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 923ffde429d71022703cb619058f94b2ae56015b0c84046e06622395bc467b56f85220d7d9ccaed790663774df13c419cfbc3c212b8a51e834ca6625b30f56d1

test:
  secret_key_base: 0b6e0e8e9453449ba801c89f5409bd7ec5d53b46d5ff91ac7b01fb5941fcb12c0a95b318ad0ac6363c0ed341d24a0e05139c76682bc01d393e38f98a543a05fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
